### ISSUE TITLE
5.23.0

### ISSUE THREAD

**Issue by f1-outsourcing** [DozerDB/dozerdb-plugin#28]
I am just testing, so I could also downgrade.

**Comment by f1-outsourcing** [comment]
> I am just testing, so I could also downgrade.

Can't really downgrade db version/log is complaining.

**Comment by jmsuhy** [comment]
What are you trying to downgrade from?  If you provide more details we can give more guidance.

**Comment by f1-outsourcing** [comment]
I downgraded neo4j from 5.23 to 5.22 so I could try your plugin, but Neo4j complains about my test db being newer.

**Comment by jmsuhy** [comment]
In the 5.x versions of Neo4j core there can be breaking changes.   I believe Neo4j follows semantic versioning.

The 5.24.0 version should hopefully be ready this week. 

But I think the issue you are having is because your data was created with Neo4j 5.23.0 and you couldn’t use it for 5.22.0 - its not a plugin issue.

If that is the case - then it may work moving to 5.24.0 from 5.23.0

or you can export your data using apoc and re import it into a fresh instance of any version.

**Comment by f1-outsourcing** [comment]
> In the 5.x versions of Neo4j core there can be breaking changes. I believe Neo4j follows semantic versioning.
> 
> The 5.24.0 version should hopefully be ready this week.
> 
> But I think the issue you are having is because your data was created with Neo4j 5.23.0 and you couldn’t use it for 5.22.0 - its not a plugin issue.
> 
> If that is the case - then it may work moving to 5.24.0 from 5.23.0
> 
> or you can export your data using apoc and re import it into a fresh instance of any version.

Yes it is for sure a Neo4j issue. Looking forward to testing this week with 5.24.0

**Comment by jmsuhy** [comment]
Looks like Neo4j just released 5.24.1 now - I guess they had some issues with 5.24.0.

We will move right to the latest - as its not a big leap to move to .1

**Comment by f1-outsourcing** [comment]
@jmsuhy 

how is it going?

**Comment by jmsuhy** [comment]
We pushed the version for 5.24.2 , also, the newest push today has create,drop, start, and stop database functionality.

**Comment by f1-outsourcing** [comment]
Oh nice, I will try that.
